### ISSUE TITLE
Missing folder and files - bst (Binary Search Tree)

### ISSUE THREAD

**Issue by BrianLeip** [wadefagen/coursera#12]
In the Ordered Data Structures course, week 2, video 2.4 Binary Search Trees - Prof Fagen shows and runs code from a "bst" folder that doesn't seem to be available in this source code.
<img width="405" alt="bst folder missing" src="https://user-images.githubusercontent.com/16980550/66261518-b67eb500-e783-11e9-92db-44c1f343ee45.png">

**Comment by echuber2** [comment]
The bst directory has been added.
