### ISSUE TITLE
Missing folder and files - avl

### ISSUE THREAD

**Issue by BrianLeip** [wadefagen/coursera#13]
Similar to the missing bst folder/files, the avl folder/files are missing.  This is from lecture 3.1.2 AVL Analysis in week 3 of the Ordered Data Structures course on Coursera.
<img width="342" alt="avl folder missing" src="https://user-images.githubusercontent.com/16980550/66264284-28242680-e7b7-11e9-9e6e-aa365b90435b.png">

**Comment by echuber2** [comment]
Hi, we know -- I've been working on adding and adapting the missing files in a branch and will try to merge soon, same situation as in #12 .

**Comment by echuber2** [comment]
The avl directory has been merged now.
